name=Sernate FireHOL Blocklist Check
id=sernate_firehol_blocklist_check
author=Sernate
version=0.1.4
update_url=https://blocklist.sernate.com/sernate_firehol_blocklist_check.tar.gz
version_url=https://blocklist.sernate.com/version.txt
active=yes
menu_admin=images/menu.json
