name=Sernate FireHOL Blocklist Check
id=sernate_firehol_blocklist_check
author=Sernate
version=1.0.3
update_url=https://github.com/WeszNL/directadmin-firehol-ip-blocklist-check/releases/latest/download/sernate_firehol_blocklist_check.tar.gz
version_url=https://raw.githubusercontent.com/WeszNL/directadmin-firehol-ip-blocklist-check/main/version.txt
active=yes
installed=yes
admin_run_as=diradmin
